# Generated by Django 4.0 on 2022-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_creation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
